### PR TITLE
tas_land processing question

### PR DESCRIPTION
**Pull request by leeyap**
Hi @kdorheim,

Here is what I have so far for processing the tas_land data. 

I calculated Tgav for all of the models that have historical runs, but that's only 11/43 total model runs, so a lot of data gets excluded. How do you want me to go forward?

Thanks!

### CODE REVIEW

**Comment by kdorheim** [comment]
Awesome thanks! Do you have a list of the 11 models that you could share? Would it be easy to plot the tas global vs tas land?

**Comment by leeyap** [comment]
Yep, the models for land `tas` are:
```
 [1] "ACCESS-ESM1-5"  "CanESM5-CanOE"  "CanESM5"        "CESM2"         
 [5] "CNRM-ESM2-1"    "GFDL-ESM4"      "GISS-E2-1-G-CC" "MIROC-ES2L"    
 [9] "MPI-ESM1-2-LR"  "MRI-ESM2-0"     "UKESM1-0-LL" 
```

And yes, should be relatively easy to plot them against each other. I can go ahead and do that if it's okay to just do it with these 11.

**Comment by kdorheim** [comment]
Yup please do this with the 11 models!

**Comment by leeyap** [comment]
@kdorheim 

Here is a sample graph, let me know what you think!

image

As expected, `tas_land` is slightly higher. There was one model ("MPI-ESM1-2-LR") that had exceptionally low values, much lower than the rest of the `tas_land` models and even lower than regular `tas`. Not sure why, but I can look into it.

**Comment by leeyap** [comment]
@kdorheim going to merge, if that's okay with you!

**Comment by kdorheim** [comment]
looks great thanks!

**Pull request merged**
